name: 'zackmart'
version: '1.0.0'

profile: 'zackmart'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  zackmart:
    +schema: L3_CONSUMPTION 
    # Config indicated by + and applies to all files under models/example/
    profit_us:
      +schema: TRAINING
      +materialized: table
    profit_uk:
      +schema: TRAINING
      +materialized: table
    profit_india:
      +schema: TRAINING
      +materialized: table
    customers_stg:
      +schema: L2_PROCESSING
    employees_stg:
      +schema: L2_PROCESSING
    orderitems_stg:
      +schema: L2_PROCESSING
    orders_stg:
      +schema: L2_PROCESSING
    customerrevenue:
      +materialized: table

    
